### ISSUE TITLE
新增語系 API 提供給前端 i18n 做翻譯

### ISSUE THREAD

**Issue by FoxTailTofu** [Kantai235/Laravel-Template#16]
前端用 `i18next` 做多語系支援，需要後端提供語系檔案的 API

**Comment by Kantai235** [comment]
fix on a243728

`/api/lang/{lang}.json`
如果今天你丟一個系統並沒有的語言，例如 `hello.json`，我會給你 `Unknown language.` 的訊息，並且附帶 HTTP Code 404
